version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  ApplicationStop:
    - location: scripts/stop_old.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/install_prereqs.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_new.sh
      timeout: 300
      runas: ubuntu