version: "3"
services:
  backend:
    build: ./backend
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
