name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin \
            526971782248.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build and push Docker images
        run: |
          # Frontend
          docker build -t my-fullstack-app-frontend ./frontend
          docker tag my-fullstack-app-frontend:latest 526971782248.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-fullstack-app:frontend
          docker push 526971782248.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-fullstack-app:frontend

          # Backend
          docker build -t my-fullstack-app-backend ./backend
          docker tag my-fullstack-app-backend:latest 526971782248.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-fullstack-app:backend
          docker push 526971782248.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-fullstack-app:backend

      - name: Zip App for CodeDeploy
        run: zip -r release.zip . 

      - name: Upload to S3
        run: aws s3 cp release.zip s3://${{ secrets.S3_BUCKET }}/release.zip

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
            --deployment-group-name ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP }} \
            --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=release.zip
